# Generated by Django 4.1.7 on 2023-11-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
    ]
