# Generated by Django 4.1.7 on 2023-11-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_address_mobile'),
        ('product', '0006_rename_created_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickup_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.address'),
        ),
    ]
